### ISSUE TITLE
naming : stesswave or stresswave ?

### ISSUE THREAD

**Issue by marcodelapierre** [seqeralabs/nf-stresswave#1]
I love 'stesswave', it adds some Piedmontese vibes, but `stresswave` may be the good one!

**Comment by pditommaso** [comment]
<img src="https://media3.giphy.com/media/26n6Gx9moCgs1pUuk/giphy.gif"/>

**Comment by marcodelapierre** [comment]
@pditommaso  you should be honorary be nominated Seqera's CMO - M as in Meme
